### ISSUE TITLE
spelfout "gmail"

### ISSUE THREAD

**Issue by ghost** [Sascha-davidson/connect-your-tribe-profile-card#1]
https://github.com/Sascha-davidson/connect-your-tribe-profile-card/blob/49a49624c4688f7f422fcf5089c00a97e54c5791/views/index.ejs#L20

**Comment by Sascha-Davidson** [comment]
https://github.com/Sascha-davidson/connect-your-tribe-profile-card/blob/main/views/index.ejs#L20

ik heb het aangepast
