### ISSUE TITLE
Bio

### ISSUE THREAD

**Issue by ju5tu5** [Sascha-davidson/connect-your-tribe-profile-card#2]
Haal je bio ook uit whois.fdnd.nl

**Comment by Sascha-Davidson** [comment]
https://github.com/Sascha-davidson/connect-your-tribe-profile-card/blob/main/views/index.ejs#L27

ik haal mijn info van mij bio uit de whois.fdnd.nl
Het ziet er misschien anders uit omdat ik er `html` achter moet plaatsen
